apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - spring-boot
    - tradeflow
spec:
  type: service
  lifecycle: production
  owner: group:default/tradeflow-team
  system: tradeflow